### ISSUE TITLE
Certification doesn't work

### ISSUE THREAD

**Issue by VII86** [kpalang/mirth-sample-plugin#10]
Hi, sorry to trouble you.
When executing the guide to build the sample project, everything works fine until the plugin is installed and the server restartet.

Trying to log in yield the following error:
`com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file mirthpluginsample-client.jar
java.util.concurrent.ExecutionException: com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file mirthpluginsample-client.jar
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at com.mirth.connect.client.launcher.f.a(SourceFile:416)
	at com.mirth.connect.client.launcher.f.a(SourceFile:371)
	at com.mirth.connect.client.launcher.MirthClientLauncher.run(SourceFile:1326)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file mirthpluginsample-client.jar
	at com.mirth.connect.client.launcher.r.a(SourceFile:266)
	at com.mirth.connect.client.launcher.r.a(SourceFile:204)
	at com.mirth.connect.client.launcher.f.a(SourceFile:542)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file mirthpluginsample-client.jar
	at com.mirth.connect.client.launcher.r.a(SourceFile:253)
	... 6 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi_8.engineValidate(Unknown Source)
	at java.base/java.security.cert.CertPathValidator.validate(Unknown Source)
	at com.mirth.connect.client.launcher.r.a(SourceFile:351)
	at com.mirth.connect.client.launcher.r.a(SourceFile:245)
	... 6 more`

I guess the self-signed certificate provided in the plugin is not valid any more?
What are the steps to create a own self-signed certificate?

Thanks a lot!

**Comment by kpalang** [comment]
You're probably using the launcher, but in it's regular more where it's quite strict in which certificates it trusts. You should find the solution [here](https://github.com/kpalang/mirth-plugin-guide?tab=readme-ov-file#pay-attention-here) :wink:

**Comment by VII86** [comment]
Thank you for your response.
I found the -k switch in the meantime as well. Works now for me.

Is there any way to circumvent needing to use the -k switch? 
I fear I'd have to have a certificate validated by NextGen?
